### ISSUE TITLE
iot_bsp_fs_open(./WifiProvStatus) = -1208

### ISSUE THREAD

**Issue by tgift00** [toddaustin07/rpi-st-device#3]
Im getting this error when trying to onboard the example device.  I have tried the onboarding on both 32 and 64 bit versions and get the same error.  I did notice you posted something in the Smartthings community sometime ago but it appears there was never a response.  At least that I could find.

E [IoT]: _iot_security_be_bsp_fs_load_from_nv(129) > iot_bsp_fs_open(./WifiProvStatus) = -1208

**Comment by toddaustin07** [comment]
Hi- no power and bitter cold;  will comment more when I can but looks like prior provisioning failed.  You’ve retried?  Do you get to point on mobile where you select an ssid?  Post log if you can.

**Comment by tgift00** [comment]
I hope you were able to dig out!  After reading your response I started over by deleting my project and rebuilding both the project, deploying to test, and rebuilding the example application and was still not able to get through the onboarding process.  I have attached my console log.
[Consolelog.txt](https://github.com/toddaustin07/rpi-st-device/files/5990105/Consolelog.txt)

**Comment by tgift00** [comment]
And yes I've retried a number of times and did get where it asked me for the SSID.

**Comment by toddaustin07** [comment]
Hi - Sorry for the delay; just got power back this morning and it's still going in out.  May be like that for another day, so I might continue to be slow in responding.

A couple things from looking at your logfile.  It appears you were already in AP mode when you started the example app, but unless you intentionally have your wireless in AP mode all the time, I suspect that you had a previous failure and it left your wireless device in the AP state.  If that's the case, you'll see up and down arrows in the wireless icon in the upper right instead of the usual live wireless 'waves' symbol.   To correct this, if you have a failure either wait for the device app to timeout and it it will restore your wireless back to station mode for you (this can take 30 seconds or more); OR if you Ctrl-c before then, run the /rpi-st-device/resetAP utility to get your wireless back to station mode before you re-run the app.  

If by chance your wireless is normally in AP mode all the time- that's actually OK; things should still work, but I wanted to point this out.

The real problem seems to be an error reported by hostapd when it is started up:

I [IoT]: _SoftAPControl(1286) > [rpi] SoftAP service stop issued
Job for hostapd.service failed because the control process exited with error code.
See "systemctl status hostapd.service" and "journalctl -xe" for details

Did you try doing a systemctl status hostapd to find out the error?  See what you can find out there and let me know.

Had you tested hostapd and dnsmasq prior to this to make sure they were working ok on your system?

Also, please post;

1) Your /etc/hostapd/hostapd.conf file as it is after you get the error so I can see if it was updated correctly
2)  your two json files: device_info and onboarding_config so I can check to make sure they look OK.

**Comment by tgift00** [comment]
Glad to hear you are back up and weathered the storm even if it is intermittent.  Here are the files you asked for.  I do have my Pi in AP mode all the time while I try to figure this out.  Seemed like the easiest approach at the time.  I have also included another console log that does not have the error you previously pointed out.  I have run this so many times with varying results I'm really not sure where to go.  I'm assuming the first error message I encountered "E [IoT]:  
_iot_security_be_bsp_fs_load_from_nv(129) > iot_bsp_fs_open(./WifiProvStatus) = -1208" is a red herring and should not be considered an issue.  If that is the case it seems to me my issue is with ST waiting on the following: "I [IoT]: _es_confirm_check_manager(783) > The button confirmation is requested".  This is where it consistently times out and I get the following errors after the timeout.

E [IoT]: _es_confirm_check_manager(793) > confirm failed
D [IoT]: iot_os_eventgroup_set_bits(315) > already set 0x08x
E [IoT]: iot_easysetup_request_handler(1784) > failed to handle step 2 (-524)

I honestly have not really dived into the "new dev platform" code and capabilities yet so a bit of a newbi in that respect.  Your help is greatly appreciated.  I would also like to stay on the Pi, just because it's fun!

[device_info.json.txt](https://github.com/toddaustin07/rpi-st-device/files/5999304/device_info.json.txt)
[hostapd.conf.txt](https://github.com/toddaustin07/rpi-st-device/files/5999305/hostapd.conf.txt)
[onboarding_config.json.txt](https://github.com/toddaustin07/rpi-st-device/files/5999306/onboarding_config.json.txt)
[Example log File 64bit - 2021-02-17.txt](https://github.com/toddaustin07/rpi-st-device/files/5999356/Example.log.File.64bit.-.2021-02-17.txt)

**Comment by tgift00** [comment]
Sorry I hit send to soon.

Yes, I have it working as an AP without issue on both the 32 and 64 bit versions and have been diagnosing various issues as they have arised throughout my testing and running my phone through my pi as it's only wifi in the house (you really get to understand how slow a Pi really is).  At this point I am pretty much set up exactly as outlined in this documentation which is very similar to how you recommend.  https://www.raspberrypi.org/documentation/configuration/wireless/access-point-routed.md

**Comment by toddaustin07** [comment]
Thanks for the info.  One more file to post if you don't mind:  /etc/dnsmasq.conf. 

I see you've got some slightly different parameters setup up in your hostapd file, but if you are confident they aren't the source of your issues, then we'll look passed that.  The fact that you are getting all the way to getting the AP list displayed on your phone says that the SoftAP functionality seems to be working ok, although it's still possible a config problem with dnsmasq or hostapd could be messing things up.  

From what I can see, it's crapping out before the SoftAP process can complete.  Run /rpi-st-device/STProv in the example app directory (or STProv64) to see what provisioning data has completed and let me know what you find.  

Looks like you have a number of APs active in your location; if you need, to try to keep a distance from any routers potentially competing at an adjacent channel number as you have set for your Pi AP.  And be sure to keep you phone close to your Pi during the provisioning process.

Shortly after you select your AP in the mobile app, what should happen is for the Pi AP to be reset to it's prior state (it really doesn't matter what AP you had selected since it's not going to try to connect to it since you are in fulltime AP mode) and then the core SDK connects with the SmartThings MQTT server.  This should happen over ethernet (hopefully you have nothing unusual configured for your ethernet?).  It can then take up to 40 seconds or more for this part of the process to complete, so make sure you give it enough time.   Pretty much the last thing that happens is that the SmartThings server completes the registration process and a device ID is given back to the Pi.  So the device ID field in the STProv output is usually the last thing to get filled in.

One other thought, I've seen sometimes if failures occur it may be necessary to delete those provisioning files that get created in the example directory, so you are starting out clean.  Yes, you can get a file open error on initial execution, but those can be ignored.
I'm referring to: CloudProvStatus, WifiProvStatus, IotAPSSID, IotAPBSSID, IotAPAuthType, ServerPort, ServerURL, MiscIfo, Label, DeviceID
I don't think this is a problem you are having, though.  If it were, the core SDK code would likely error-out before it reaches SoftAP mode.

Just to confirm your configuration:
- Pi Model and OS version?
- Mobile phone type?
- SmartThings app version?

Did you use the mastersetup script to configure everything or did you do it manually?

I see you mention 64 bit version; just so you know there's been fairly limited testing on that to-date.  Definitely full-time AP configurations have NOT been tested on 64 bit but should have no problem on 32 bit.  So if you are on 64 bit and we exhaust all other ideas, I may ask you to either go back to 32 bit or put your 64 -bit wireless back to station as default.  I can try to test this myself when I have a more stable power situation.

**Comment by toddaustin07** [comment]
Hello again.  I've been able to reproduce your config: 64bit O/S + always-on AP mode and had success.  But I was able to do a side-by-side comparison of the log files and something new jumped out at me.  At about line 200 in your log there is a message saying "the button confirmation is requested".  This should not be there and sounds like it's possible you have a wrong parameter set in your device profile in Developer Workspace.

In the Device Onboarding section of the device profile setup under Instructions, the fourth page with title 'Confirm Device' gives you options for the confirm method.  MAKE SURE YOU HAVE SELECTED 'JUST WORKS'.   Right now it looks like you picked to have the user press a button, but that's not set up for Raspberry Pi - it's more for MCUs with an onboard button for resetting and such.   It looks like this was causing the core SDK to time out waiting for a button press.  I see I don't have that parameter specified in the documentation so I'll fix that.

I also realize now that I should have picked this up in your onboarding_config.json.  When you fix it in the Developer Workspace, be sure to re-download the new onboarding_config.json file to your example directory **and re-make the example app**.

I hadn't even given thought to implement support for a button press during provisioning on Pi; if you think that would be a useful feature let me know and I can explore that.  

Hopefully this is the source of your problem.  Let me know!

**Comment by tgift00** [comment]
That may be it.  I have tried multiple times today with no success.  I'll give that a shot and let you know.  If it doesn't work I'll post the additional info you were looking for.

**Comment by tgift00** [comment]
That worked.  Thanks for your help on this.

**Comment by toddaustin07** [comment]
Awesome!  Let me know if you have any other troubles.  For now, I'll consider this one closed.
